<script lang="ts">
  import { base } from '$app/paths';
  import ContentPage from '$lib/components/ContentPage.svelte';
</script>

<svelte:head>
  <title>Terms of Service · Paper Heroes</title>
  <meta name="description" content="The terms governing your use of Paper Heroes." />
</svelte:head>

<ContentPage title="Terms of Service" updated="17 August 2026">
  <p>
    These Terms of Service ("Terms") govern your use of <strong>Paper Heroes</strong> at
    paperheroes.io. By accessing or using the site, you agree to these Terms. If you do not agree,
    please do not use the site.
  </p>

  <h2>What Paper Heroes is</h2>
  <p>
    Paper Heroes deals one recently-published medical paper at random and presents an AI-generated
    summary, critical appraisal, and illustration as a trading card. It is an educational and
    informational tool.
  </p>

  <div class="callout warn">
    <p>
      ⚠ <strong>Not medical advice.</strong> The summaries, appraisals, statistics, and
      illustrations are generated by artificial intelligence and may be incomplete, out of date, or
      wrong. Nothing on Paper Heroes is medical advice, and it must not be used to diagnose or treat
      any condition or to make clinical decisions. Always read and verify the original,
      peer-reviewed article and use your own professional judgement.
    </p>
  </div>

  <h2>Accounts</h2>
  <ul>
    <li>
      Registration requires a valid email address and professional registration details. You are
      responsible for keeping your account and sign-in link secure and for activity under your
      account.
    </li>
    <li>
      Accounts and paid features are provided on an as-is basis. Tier upgrades on the site are
      currently <strong>simulated</strong> and no payment is taken.
    </li>
    <li>We may suspend or terminate accounts that misuse the service or breach these Terms.</li>
  </ul>

  <h2>Acceptable use</h2>
  <ul>
    <li>Do not use the site unlawfully, or to infringe the rights of others.</li>
    <li>
      Do not attempt to disrupt, overload, scrape at scale, reverse-engineer, or circumvent access
      controls or rate limits.
    </li>
    <li>Do not submit content that is unlawful, abusive, or infringing through the contact form or reflections.</li>
  </ul>

  <h2>Your content</h2>
  <p>
    You retain ownership of the reflections and other content you create. You grant us the limited
    right to store and display that content back to you as part of providing the service.
  </p>

  <h2>Intellectual property</h2>
  <p>
    Article abstracts and metadata are the property of their respective publishers and authors and
    are retrieved from PubMed for the purpose of summary and appraisal. AI-generated summaries and
    illustrations are provided for personal, educational use. The Paper Heroes name, design, and
    software are ours.
  </p>

  <h2>Advertising</h2>
  <p>
    The site displays third-party advertising (Google AdSense). We are not responsible for the
    content of ads or the sites they link to. See our <a href="{base}/privacy">Privacy Policy</a> for
    how advertising cookies are used.
  </p>

  <h2>Disclaimers and limitation of liability</h2>
  <p>
    The service is provided "as is" and "as available", without warranties of any kind, express or
    implied, including accuracy, fitness for a particular purpose, or non-infringement. To the
    fullest extent permitted by law, we are not liable for any loss or damage arising from your use
    of, or reliance on, the site or its AI-generated content.
  </p>

  <h2>Changes to the service and these Terms</h2>
  <p>
    We may change, suspend, or discontinue any part of the service at any time. We may also update
    these Terms; material changes will be reflected by the "last updated" date above. Continued use
    after a change means you accept the updated Terms.
  </p>

  <h2>Contact</h2>
  <p>
    Questions about these Terms? Reach us through the <a href="{base}/#contact">contact form</a>. See
    also our <a href="{base}/privacy">Privacy Policy</a>.
  </p>
</ContentPage>
